### PR TITLE
Better character escaping / sentence support.

### PR DESCRIPTION
**Pull request by sakshamsharma**
I was tempted to use std::quoted, but it doesn't handle single quoted
strings like shells do.

Also, this particular form of escaping allows accepting json strings as
input easily (because now we can do things like: `'{"a": "b"}'`).

### CODE REVIEW

**Comment by daniele77** [comment]
Could you please add the relevant tests in `cli/test/test_split.cpp`?
Thanks

**Comment by daniele77** [comment]
Fixed a little issue, added some test and merged.
Thank you very much for your contribution!

**Comment by sakshamsharma** [comment]
I actually had some more local changes to this change that I hadn't found time to push yet, sorry it got delayed. I will put up another Pull Request when I get some time.

**Comment by daniele77** [comment]
Very good. Just start from the current head master of repo and add the proper tests.

**Pull request merged**
