### PR TITLE
Replaced Boost.Asio with Asio (much smaller library)

### PR DESCRIPTION
**Pull request by connorjak**
This was much easier than I expected. I basically just messed with the namespaces to rearrange things to depend on Asio instead of Boost. I had to change boost::system::error_code to std::error_code in a few places, but that's consistent with the other differences of Boost-less Asio. More info on that: https://think-async.com/Asio/AsioAndBoostAsio.html

I wasn't able to get tests working immediately because I had some issues with my local Boost library. I did try the Windows examples, though, and they all worked!

### CODE REVIEW

**Comment by connorjak** [comment]
Update: I fixed my local Boost, and the tests I did on Windows 10 x64 succeeded.

**Comment by connorjak** [comment]
I can't really decipher what's going wrong now; I can't get Visual Studio to spin up a proper WSL ubuntu dev environment for me.

**Comment by thegwydd** [comment]
@connorjak I was going to make the same type of modifications you've done and I saw your pull request.
Just a consideration. 
Instead of dropping boost dependency (I always agree in eliminating boost dependency) you could replace all boost::asio::something with the macro ASIO_NS that depends on what's given from the build environment.
I means something like this:

#ifdef USE_BOOST // from build system vars
#   include <boost/asio.hpp>
#   define ASIO_NS boost::asio
#else
#   include <asio/asio.hpp>
#   define ASIO_NS asio
#endif

This would allow who wants to use boost to keep using it (-DUSE_BOOST) and who don't want boost can use original asio.
What do you think?

**Comment by daniele77** [comment]
Hey guys,
first of all, thank you very much for the work you're doing.

As I said elsewhere, (see issue #41) my plan is the following:
- remove boost from the library
- confine the use of boost or asio in the "remote session" (i.e. the telnet server).

Just a couple of remarks:
- the remote server is a class and it should be replaceable (through polymorphism or template parameter) with implementations using boost, asio, or whatever socket library. So I'd prefer the choice between boost and asio was made through the inclusion of appropriate header files (e.g., `#include "cli/boost_asio_remoteserver.h"` vs `#include "cli/asio_remoteserver.h"`) instead of using preprocessor macros. 
- currently, the library uses boost as an async engine (see reactor pattern) also for local sessions. This means the library user is required to run `asio::io_context::run()` in his thread to have the cli callbacks running in that thread.

I'm working to solve these issues, to eventually get rid of boost libraries  (for those who want to) thus making the library suitable for everyone. If you want, we can work together on this goal after thinking about how to do it and how to proceed.

**Comment by thegwydd** [comment]
I've forked the project and done few modifications (I'm quite near to request a pull).
- used macro for asio namespace (boost and non boost version)
- modified cmakelists to allow configuration of boost and non-boost version
- fixed all code to be C11 ready (just few mods)
- added conan.io recipe and modified cmakelists to optionally use conan packages for asio

there's need for some testing but right now the new version works in my project (non boost asio/c++11 on gcc 4.9.2)

**Pull request closed without merging**
