### PR TITLE
Redesigned the function handle template for Menu::Add() to allow for arbitrary arguments

### PR DESCRIPTION
**Pull request by JeremyAgostGC**
The existing code had separate implementations of the FuncCmd wrapper that could handle 0 to 4 arguments passed from the command parser into the handler. This mechanism has been replaced with some relatively simple TMP based on a template parameter pack. 

You can now specify a command handler callable that takes any number of arguments. It's also easier to customize the display of help text for these arguments. The following pattern implemented before the menu items are instantiated will allow custom prompt text to be displayed even if the arguments are the same base type.
```
namespace cli {
	namespace argtypes {
		struct device : public std::string {};
		struct filename : public std::string {};
	}
	template <> struct TypeDesc<argtypes::device> { static const char* Name() { return "<device>"; } };
	template <> struct TypeDesc<argtypes::filename> { static const char* Name() { return "<filename>"; } };
}
```

```
rootMenu->Add("do-something",
	[service](std::ostream & out, cli::argtypes::device identifier){ performAction(identifier, "", out); });
rootMenu->Add("do-something",
	[service](std::ostream & out, cli::argtypes::device identifier, cli::argtypes::filename filename){ performAction(identifier, filename, out); },
	"Perform the action on the device with the file");
```

You'll get the following help text:
```
 - do-something <device>
 - do-something <device> <filename>
	Perform the action on the device with the file
```

The implementation relies on `std::apply()` as specified by C++17 so I've relicensed a portion of my C++17 compatibility layer and included it for configurations where `std::experimental::apply()` isn't available.

The reordering of the arguments in the command handler declaration, with the ostream parameter coming first is intentional. This is necessary to reduce ambiguity with the variadic arguments. If the description field is an empty string, an empty newline is not printed for that command. This makes it cleaner to specify overloads of command names that take slightly different arguments.

### CODE REVIEW

**Comment by daniele77** [comment]
Thank you very much, @JeremyAgost : at first glance, your contribution seems very interesting.
In the next days, I have to check it more deeply.

I understand that the reordering of the arguments is needed (and BTW yours is the correct order I should have implemented from the very beginning, unfortunately I did wrong instead :-( ). This change, however, represents a public API change, so it would break all existing code. This could be a problem.

My second doubt concerns the opportunity to import so many code to re-implement `std::apply`. I have to think about this...

Anyway: your contribution adds something useful. Thank you again.

**Comment by JeremyAgostGC** [comment]
Changing the API of course seems drastic, especially since you just recently released a 1.0 version. I hope you’d agree though that a var-args implementation that relies on hardcoded specializations to handle different numbers of arguments is a complete dead end and doesn’t belong in a C++ library! 

Unfortunately, it’s not uncommon that complex TMP often ends up depending on C++17 features. Because of poor compiler support, my organization is still on C++14 (though we’re switching soon!) and thus we decided to develop a compatibility shim library that backports several useful C++17 features based on the implementation examples from the standard and libc++. I relicensed and repackaged some of those shim headers from my org to submit them alongside this feature because  didn’t want to blithely submit a pull request that forces your project to require C++17 :)

**Comment by daniele77** [comment]
@JeremyAgostGC I agree about everything.
Let me some time to analyze your code and think about the opportunity to break the APIs.
In some ways, I’d like to use your PR

**Comment by JeremyAgostGC** [comment]
Thanks :) we’re using this feature in our fork and I wanted to make sure I could rebase and push upstream just in case it was helpful for you!

**Comment by daniele77** [comment]
Eventually, I managed to achieve the same exact thing (i.e., an arbitrary number of arguments in `Menu::Add()` through variadic templates) without tuples and `std::apply`, using the old technique of compile time recursion on the template arguments instead.

In this way, the LOC counter went down a lot with respect to the `std::tuple` and `std::apply `implementation.

You can find the new version in the branch `variadic_template_in_add_cmds_func` e.g., at the commit SHA: bc9bb4fada5e143facd6f915cbc202bd849c76f5

Some notes about that commit:
- I added the variadic template method and kept the old one `Menu::Add()` deprecated through attribute `[[deprecated]]`
- I used the name `Menu::_Add` for the new method, just for the moment. I'm going to change it to `Add::Insert()`, `Add::Attach()` or something like that (attach can be better because in the future I'll have a method to dynamically remove a command)
- I added an (optional) argument for the description of the arguments. The solution based on types doesn't work for primitive types and requires more code client side.

I guess I'll merge the branch on the master soon, I'd like however to have comments from you about this code.

Thanks again.

**Comment by daniele77** [comment]
Eventually, I added to master branch my solution that doesn't require std::tuple nor apply. Moreover, the code is much shorted this way.
To provide backward compatibility, I added the new method `Menu::Insert` and deprecated `Menu::Add`.

**Pull request closed without merging**
